name: ruby_ci

on: [push]

jobs:
  build:
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundle-cache: true
    - run: bundle exec rspec
